import type { VerbCard } from './config/verbs';

export const verbData: VerbCard[] = [
  {
    id: '1',
    infinitive: 'machen',
    englishMeaning: 'to do / make',
    presentThirdPerson: 'macht',
    pastParticiple: 'gemacht',
    auxiliary: 'haben',
    exampleGerman: 'Er hat seine Hausaufgaben gemacht.',
    exampleEnglish: 'He did his homework.',
    isIrregular: false,
    level: 'A1'
  },
  {
    id: '2',
    infinitive: 'fahren',
    englishMeaning: 'to drive / go (by vehicle)',
    presentThirdPerson: 'fährt',
    pastParticiple: 'gefahren',
    auxiliary: 'sein',
    exampleGerman: 'Wir sind nach Berlin gefahren.',
    exampleEnglish: 'We drove to Berlin.',
    isIrregular: true,
    level: 'A1'
  }
];

export const mostUsed100 = [
  {
    infinitive: "sein",
    englishMeaning: "to be",
    type: "irregular/strong",
    separable: false,
    auxiliary: "sein",
    forms: { present: "ist", past: "war", perfect: "gewesen" }
  },
  {
    infinitive: "haben",
    englishMeaning: "to have",
    type: "irregular/mixed",
    separable: false,
    auxiliary: "haben",
    forms: { present: "hat", past: "hatte", perfect: "gehabt" }
  },
  {
    infinitive: "werden",
    englishMeaning: "to become",
    type: "irregular/strong",
    separable: false,
    auxiliary: "sein",
    forms: { present: "wird", past: "wurde", perfect: "geworden" }
  },
  {
    infinitive: "sagen",
    englishMeaning: "to say",
    type: "regular",
    separable: false,
    auxiliary: "haben",
    forms: { present: "sagt", past: "sagte", perfect: "gesagt" }
  },
  {
    infinitive: "anfangen",
    englishMeaning: "to begin",
    type: "strong",
    separable: true,
    auxiliary: "haben",
    forms: { present: "fängt an", past: "fing an", perfect: "angefangen" }
  },
  { infinitive: "können", englishMeaning: "can/to be able to", type: "modal" },
  { infinitive: "müssen", englishMeaning: "must/to have to", type: "modal" },
  { infinitive: "machen", englishMeaning: "to do/make", type: "regular" },
  { infinitive: "geben", englishMeaning: "to give", type: "strong" },
  { infinitive: "kommen", englishMeaning: "to come", type: "strong" },
  { infinitive: "sollen", englishMeaning: "should", type: "modal" },
  { infinitive: "wollen", englishMeaning: "to want", type: "modal" },
  { infinitive: "gehen", englishMeaning: "to go", type: "strong" },
  { infinitive: "wissen", englishMeaning: "to know (facts)", type: "mixed" },
  { infinitive: "sehen", englishMeaning: "to see", type: "strong" },
  { infinitive: "lassen", englishMeaning: "to let/allow", type: "strong" },
  { infinitive: "stehen", englishMeaning: "to stand", type: "strong" },
  { infinitive: "finden", englishMeaning: "to find", type: "strong" },
  { infinitive: "bleiben", englishMeaning: "to stay", type: "strong" },
  { infinitive: "liegen", englishMeaning: "to lie (position)", type: "strong" },
  { infinitive: "heißen", englishMeaning: "to be called", type: "strong" },
  { infinitive: "denken", englishMeaning: "to think", type: "mixed" },
  { infinitive: "nehmen", englishMeaning: "to take", type: "strong" },
  { infinitive: "tun", englishMeaning: "to do", type: "irregular" },
  { infinitive: "dürfen", englishMeaning: "may/to be allowed", type: "modal" },
  { infinitive: "glauben", englishMeaning: "to believe", type: "regular" },
  { infinitive: "halten", englishMeaning: "to hold/stop", type: "strong" },
  { infinitive: "nennen", englishMeaning: "to name", type: "mixed" },
  { infinitive: "mögen", englishMeaning: "to like", type: "modal" },
  { infinitive: "zeigen", englishMeaning: "to show", type: "regular" },
  { infinitive: "führen", englishMeaning: "to lead", type: "regular" },
  { infinitive: "sprechen", englishMeaning: "to speak", type: "strong" },
  { infinitive: "bringen", englishMeaning: "to bring", type: "mixed" },
  { infinitive: "leben", englishMeaning: "to live", type: "regular" },
  { infinitive: "fahren", englishMeaning: "to drive/go", type: "strong" },
  { infinitive: "meinen", englishMeaning: "to mean/think", type: "regular" },
  { infinitive: "fragen", englishMeaning: "to ask", type: "regular" },
  { infinitive: "kennen", englishMeaning: "to know (people/places)", type: "mixed" },
  { infinitive: "gelten", englishMeaning: "to be valid", type: "strong" },
  { infinitive: "stellen", englishMeaning: "to place/put", type: "regular" },
  { infinitive: "spielen", englishMeaning: "to play", type: "regular" },
  { infinitive: "arbeiten", englishMeaning: "to work", type: "regular" },
  { infinitive: "brauchen", englishMeaning: "to need", type: "regular" },
  { infinitive: "folgen", englishMeaning: "to follow", type: "regular" },
  { infinitive: "lernen", englishMeaning: "to learn", type: "regular" },
  { infinitive: "bestehen", englishMeaning: "to exist/insist/pass", type: "strong" },
  { infinitive: "verstehen", englishMeaning: "to understand", type: "strong" },
  { infinitive: "setzen", englishMeaning: "to set/sit down", type: "regular" },
  { infinitive: "bekommen", englishMeaning: "to receive", type: "strong" },
  { infinitive: "beginnen", englishMeaning: "to begin", type: "strong" },
  { infinitive: "erzählen", englishMeaning: "to tell/narrate", type: "regular" },
  { infinitive: "versuchen", englishMeaning: "to try", type: "regular" },
  { infinitive: "schreiben", englishMeaning: "to write", type: "strong" },
  { infinitive: "laufen", englishMeaning: "to run", type: "strong" },
  { infinitive: "erklären", englishMeaning: "to explain", type: "regular" },
  { infinitive: "entsprechen", englishMeaning: "to correspond", type: "strong" },
  { infinitive: "sitzen", englishMeaning: "to sit", type: "strong" },
  { infinitive: "ziehen", englishMeaning: "to pull/move", type: "strong" },
  { infinitive: "scheinen", englishMeaning: "to shine/seem", type: "strong" },
  { infinitive: "fallen", englishMeaning: "to fall", type: "strong" },
  { infinitive: "gehören", englishMeaning: "to belong", type: "regular" },
  { infinitive: "entstehen", englishMeaning: "to originate", type: "strong" },
  { infinitive: "erhalten", englishMeaning: "to receive", type: "strong" },
  { infinitive: "treffen", englishMeaning: "to meet", type: "strong" },
  { infinitive: "suchen", englishMeaning: "to search", type: "regular" },
  { infinitive: "legen", englishMeaning: "to lay/put", type: "regular" },
  { infinitive: "vorstellen", englishMeaning: "to introduce/imagine", type: "separable" },
  { infinitive: "handeln", englishMeaning: "to act/deal", type: "regular" },
  { infinitive: "erreichen", englishMeaning: "to reach", type: "regular" },
  { infinitive: "tragen", englishMeaning: "to wear/carry", type: "strong" },
  { infinitive: "schaffen", englishMeaning: "to create/manage", type:"regular/strong" },
  { infinitive: "lesen", englishMeaning: "to read", type: "strong" },
  { infinitive: "verlieren", englishMeaning: "to lose", type: "strong" },
  { infinitive: "darstellen", englishMeaning: "to represent", type: "separable" },
  { infinitive: "erkennen", englishMeaning: "to recognize", type: "mixed" },
  { infinitive: "entwickeln", englishMeaning: "to develop", type: "regular" },
  { infinitive: "reden", englishMeaning: "to talk", type: "regular" },
  { infinitive: "aussehen", englishMeaning: "to look like", "type":"eparable/strong" },
  { infinitive: "erscheinen", englishMeaning: "to appear", type: "strong" },
  { infinitive: "bilden", englishMeaning: "to form", type: "regular" },
  { infinitive: "erwarten", englishMeaning: "to expect", type: "regular" },
  { infinitive: "wohnen", englishMeaning: "to live/dwell", type: "regular" },
  { infinitive: "betreffen", englishMeaning: "to affect/concern", type: "strong" },
  { infinitive: "warten", englishMeaning: "to wait", type: "regular" },
  { infinitive: "helfen", englishMeaning: "to help", type: "strong" },
  { infinitive: "gewinnen", englishMeaning: "to win", type: "strong" },
  { infinitive: "schließen", englishMeaning: "to close", type: "strong" },
  { infinitive: "fühlen", englishMeaning: "to feel", type: "regular" },
  { infinitive: "bieten", englishMeaning: "to offer", type: "strong" },
  { infinitive: "interessieren", englishMeaning: "to interest", type: "regular" },
  { infinitive: "erinnern", englishMeaning: "to remind", type: "regular" },
  { infinitive: "ergeben", englishMeaning: "to result in", type: "strong" },
  { infinitive: "anbieten", englishMeaning: "to offer", type: "separable" },
  { infinitive: "studieren", englishMeaning: "to study", type: "regular" },
  { infinitive: "verbinden", englishMeaning: "to connect", type: "strong" },
  { infinitive: "ansehen", englishMeaning: "to look at", type: "separable" },
  { infinitive: "fehlen", englishMeaning: "to be missing", type: "regular" },
  { infinitive: "bedeuten", englishMeaning: "to mean", type: "regular" },
  { infinitive: "verändern", englishMeaning: "to change", type: "regular" },
  { infinitive: "dienen", englishMeaning: "to serve", type: "regular" }
];